function weathercode(wcode, ) {
    wcode = parseInt(wcode);
    if(wcode == 0)  return 'Clear sky'
    if(wcode == 1)  return 'Mainly clear'
    if(wcode == 2)  return 'Partly cloudy'
    if(wcode == 3)  return 'Overcast'
    if(wcode == 45) return 'Fog'
    if(wcode == 48) return 'Depositing rime Fog'
    if(wcode == 51) return 'Light drizzle'
    if(wcode == 53) return 'Moderate drizzle'
    if(wcode == 55) return 'Dense drizzle'
    if(wcode == 56) return 'Light Freezing drizzle'
    if(wcode == 57) return 'Dense Freezing drizzle'
    if(wcode == 61) return 'Slight Rain'
    if(wcode == 63) return 'Moderate Rain'
    if(wcode == 65) return 'Heavy Rain'
    if(wcode == 66) return 'Light Freezing rain'
    if(wcode == 67) return 'Heavy Freezing rain'
    if(wcode == 71) return 'Slight Snowfall'
    if(wcode == 73) return 'Moderate Snowfall'
    if(wcode == 75) return 'Heavy Snowfall'
    if(wcode == 77) return 'Snow grains'
    if(wcode == 80) return 'Slight Rain showers'
    if(wcode == 81) return 'Moderate Rain showers'
    if(wcode == 82) return 'Violent Rain showers'
    if(wcode == 85) return 'Slight Snow showers'
    if(wcode == 86) return 'Heavy Snow showers'
    if(wcode == 95) return 'Slight-Moderate Thunderstorm'
    if(wcode == 96) return 'Slight Hail Thunderstorm'
    if(wcode == 99) return 'Heavy Hail Thunderstorm'
}